DROP TABLE REPORTS CASCADE CONSTRAINTS;
DROP TABLE DIARY_BOX CASCADE CONSTRAINTS;
DROP TABLE DIARIES CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE ADMINS CASCADE CONSTRAINTS;
DROP TABLE CATEGORIES CASCADE CONSTRAINTS;

/* 사용자(USERS) */
CREATE TABLE USERS (
    user_no NUMBER GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR2(40)  NOT NULL,
    pw VARCHAR2(255) NOT NULL,
    key_count NUMBER DEFAULT 0 NOT NULL,
    status CHAR(1) DEFAULT 'A' NOT NULL,
    login_fail_count NUMBER DEFAULT 0 NOT NULL,
    last_failed_at DATE,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE,
    CONSTRAINT PK_USERS PRIMARY KEY (user_no)
);

/* 관리자(ADMINS) */
CREATE TABLE ADMINS (
    admin_no NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id VARCHAR2(30) NOT NULL,
    pw VARCHAR2(255) NOT NULL,
    name VARCHAR2(20) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE,
    CONSTRAINT PK_ADMINS PRIMARY KEY (admin_no)
);

/* 카테고리(CATEGORIES) - DIARIES에서 참조하므로 먼저 생성 */
CREATE TABLE CATEGORIES (
    category_no NUMBER NOT NULL, /* 자동증가 아님. 직접 입력 */
    name VARCHAR2(50)  NOT NULL, /* 카테고리명 */
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE,
    CONSTRAINT PK_CATEGORIES PRIMARY KEY (category_no)
);

/* 일기(DIARIES) */
CREATE TABLE DIARIES (
    diary_no NUMBER GENERATED BY DEFAULT AS IDENTITY,
    writer_no NUMBER,
    category_no NUMBER,
    title VARCHAR2(30) DEFAULT '제목없음' NOT NULL,
    day DATE NOT NULL,
    weather VARCHAR2(10),
    emotion CHAR(1),
    content CLOB NOT NULL,
    img_1 VARCHAR2(255),
    img_2 VARCHAR2(255),
    img_3 VARCHAR2(255),
    status CHAR(1) DEFAULT 'A',
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE,
    CONSTRAINT PK_DIARIES PRIMARY KEY (diary_no),
    CONSTRAINT FK_DIARIES_WRITER FOREIGN KEY (writer_no) REFERENCES USERS(user_no) ON DELETE SET NULL,
    CONSTRAINT FK_DIARIES_CATEGORY FOREIGN KEY (category_no) REFERENCES CATEGORIES(category_no) ON DELETE SET NULL /* 추가: 외래키 */
);

/* 일기 보관함(DIARY_BOX) */
CREATE TABLE DIARY_BOX (
    box_no NUMBER GENERATED BY DEFAULT AS IDENTITY,
    owner_no NUMBER NOT NULL,
    diary_no NUMBER NOT NULL,
    type CHAR(1) NOT NULL,
    is_important NUMBER(1) DEFAULT 0 NOT NULL,
    add_date DATE DEFAULT SYSDATE NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE,
    CONSTRAINT PK_DIARY_BOX PRIMARY KEY (box_no),
    CONSTRAINT FK_BOX_OWNER FOREIGN KEY (owner_no) REFERENCES USERS(user_no) ON DELETE CASCADE,
    CONSTRAINT FK_BOX_DIARY FOREIGN KEY (diary_no) REFERENCES DIARIES(diary_no) ON DELETE CASCADE
);

/* 신고 정보(REPORTS) */
CREATE TABLE REPORTS (
    report_no NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reporter_no NUMBER,
    diary_no NUMBER NOT NULL,
    reason CHAR(1) NOT NULL,
    content CLOB,
    status CHAR(1) DEFAULT 'C' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE,
    CONSTRAINT PK_REPORTS PRIMARY KEY (report_no),
    CONSTRAINT FK_REPORTS_REPORTER FOREIGN KEY (reporter_no) REFERENCES USERS(user_no) ON DELETE SET NULL,
    CONSTRAINT FK_REPORTS_DIARY FOREIGN KEY (diary_no) REFERENCES DIARIES(diary_no) ON DELETE CASCADE
);

/* 테이블 별 각종 제약조건 추가 쿼리 */
/* 사용자 상태 제약조건 */
/* A(Allowed, 정상), B(Banned, 정지), O(Out, 탈퇴), L(Locked, 잠김) */
ALTER TABLE USERS ADD CONSTRAINT CK_USERS_STATUS 
CHECK (status IN ('A', 'B', 'O', 'L'));

/* 일기 날씨 제약조건 */
/* sun(Sunny, 맑음), hot(Hot, 더움), cold(Cold, 추움), wind(Windy, 강풍), rain(Rainy, 비 옴), snow(Snow, 눈 옴) */
ALTER TABLE DIARIES ADD CONSTRAINT CK_DIARIES_WEATHER 
CHECK (weather IN ('sun', 'hot', 'cold', 'wind', 'rain', 'snow'));

/* 일기 감정 제약조건 */
/* N(Normal, 평범함), H(Happy, 행복함),  A(Angry, 화남), S(Sad, 우울함),  F(Fun, 즐거움) */
ALTER TABLE DIARIES ADD CONSTRAINT CK_DIARIES_EMOTION 
CHECK (emotion IN ('N', 'H', 'A', 'S', 'F'));

/* 일기 상태 제약조건 */
/* A(Allowed, 정상), B(Banned, 부적절한 내용으로 차단된 일기) */
ALTER TABLE DIARIES ADD CONSTRAINT CK_DIARIES_STATUS 
CHECK (status IN ('A', 'B'));

/* 보관함 유형 제약조건 */
/* m(me. 내가 작성한 일기), o(other, 다른 사람이 작성한 일기) */
ALTER TABLE DIARY_BOX ADD CONSTRAINT CK_BOX_TYPE 
CHECK (type IN ('m', 'o'));

/* 보관함 중요 여부 제약조건 (0, 1) */
/* 1일 경우 중요한 일기, 0일 경우 중요하지 않은 일기. */
ALTER TABLE DIARY_BOX ADD CONSTRAINT CK_BOX_IMPORTANT 
CHECK (is_important IN (0, 1));

/* 신고 사유 제약조건 */
/* G(gore, 잔혹하거나 혐오감을 주는 일기), H(hate, 누군가를 혐오하거나 증오하는 내용), E(erotic, 선정적인 내용), 
C(crime, 법에 위반되는 내용이 적히거나 범죄와 관련된 내용의 일기), L(language, 우회된 욕설 등 잘못된 언어 표현), M(category-miss, 주제와 맞지 않는 내용의 일기)*/
ALTER TABLE REPORTS ADD CONSTRAINT CK_REPORTS_REASON 
CHECK (reason IN ('G', 'H', 'E', 'C', 'L', 'M'));

/* 신고 처리 상태 제약조건 */
/* C(checked, 확인 중), B(banned, 차단된 일기), P(pass, 확인한 결과 문제 없는 내용)  */
ALTER TABLE REPORTS ADD CONSTRAINT CK_REPORTS_STATUS 
CHECK (status IN ('C', 'B', 'P'));